"""
Killer perk data — all 139 killer perks, rated per Odds' 9.6.0 tier list.
Tiers: Excellent (5★), Very Good (4★), Decent (3★), Weak/Niche (2★), Terrible (1★)
"""

# (id, tier, name, character, category, description)
KILLER_PERKS_RAW = [

    # ══ Excellent (5★) ═══════════════════════════════════════════════════════

    (1001, "Excellent", "Corrupt Intervention", "Plague", "Gen Control",
     "Blocks the 3 furthest generators for 2 minutes; forces survivors into your side of the map during the critical early game regardless of your skill level."),
    (1002, "Excellent", "Scourge Hook: Pain Resonance", "Artist", "Gen Control",
     "Hooking a survivor on a Scourge Hook instantly explodes the highest-progress generator; arguably the best hook-synergy gen-regression perk in the game."),
    (1003, "Excellent", "Dead Man's Switch", "Deathslinger", "Gen Control",
     "While carrying a survivor, any generator a survivor abandons is blocked until the carry ends; pairs perfectly with Scourge Hook: Pain Resonance to lock gens."),
    (1004, "Excellent", "Hex: Ruin", "Hag", "Hex",
     "Unattended generators slowly regress; forces teams to constantly repair rather than split-push, especially brutal on indoor maps with long travel times."),
    (1005, "Excellent", "Hex: Thrill of the Hunt", "General (all killers)", "Hex",
     "Slows all totem-cleansing by 20-40% and notifies you each time a totem is cleansed; protects other hexes and gives intel on survivor totem runs."),
    (1006, "Excellent", "Turn Back the Clock", "The First / Henry Creel", "Gen Control",
     "After hooking a survivor, activate within 20 m to explode a generator and start regression; reliable targeted gen pressure on every hook."),
    (1007, "Excellent", "Eruption", "Nemesis", "Gen Control",
     "Injuring a survivor near a Scourge Hook causes nearby generators to violently explode; pairs with hit-heavy killers for devastating area gen pressure."),
    (1008, "Excellent", "Pop Goes the Weasel", "Clown", "Gen Control",
     "Kicking a generator within 35 seconds of a hook instantly removes 20% progress; the most consistent on-demand gen-regression perk available."),

    # ══ Very Good (4★) ═══════════════════════════════════════════════════════

    (1009, "Very Good", "Grim Embrace", "Artist", "Gen Control",
     "Hooking all 4 survivors once blocks every generator for 30 seconds and reveals the obsession; snowballs strongly when you rotate hooks efficiently."),
    (1010, "Very Good", "Deadlock", "Cenobite / Pinhead", "Gen Control",
     "Each completed generator causes the next highest-progress generator to block for 30 seconds; automatically punishes gen-rush coordination."),
    (1011, "Very Good", "Hex: Undying", "Blight", "Hex",
     "When another hex totem is cleansed, its effect transfers here; gives your best hex a second life and reveals survivors who cleanse near it."),
    (1012, "Very Good", "No Way Out", "Trickster", "End-Game",
     "Each first-time hook adds a token delaying exit gate opening at end-game; stacks to a devastating 60-second delay that can close out close matches."),
    (1013, "Very Good", "Hex: No One Escapes Death", "General (all killers)", "End-Game",
     "After all generators complete, gain Exposed status and a speed boost until a dull totem is cleansed; reliable free comeback mechanic every match."),
    (1014, "Very Good", "Lethal Pursuer", "Nemesis", "Information",
     "Reveals all survivor auras for 9 seconds at match start; the best opening information perk to immediately locate your first chase target."),
    (1015, "Very Good", "Hex: Blood Favour", "Blight", "Hex",
     "During a chase after a survivor drops a pallet, block that pallet for 3 seconds; brutally effective at pallet-heavy tiles, makes many loops unsafe."),
    (1016, "Very Good", "Hex: Hive Mind", "The First / Henry Creel", "Hex",
     "Converts a dull totem; when 4 generators are completed, all remaining generators explode simultaneously; punishes fast gen-rushing teams in late game."),
    (1017, "Very Good", "Nowhere to Hide", "Knight", "Information",
     "Kicking a generator reveals all survivor auras within 24 m for 6 seconds; outstanding information that makes every gen kick doubly valuable."),
    (1018, "Very Good", "Agitation", "Trapper", "Utility",
     "Increases movement speed and reduces struggle effects while carrying a survivor; near-mandatory for basement builds and anti-rescue strategies."),
    (1019, "Very Good", "Barbecue & Chilli", "Cannibal / Bubba", "Information",
     "After hooking a survivor, all other survivors' auras are revealed for 4 seconds; the best passive information perk for finding your next target after every hook."),
    (1020, "Very Good", "Tinkerer", "Hillbilly", "Information",
     "When a generator reaches 70% progress, gain Undetectable for 12 seconds and a notification; lets you silently ambush survivors on key gens."),
    (1021, "Very Good", "Secret Project", "The First / Henry Creel", "Gen Control",
     "When a totem is blessed or cleansed, block random generators for 20-30 seconds and gain Undetectable; heavily punishes any totem interaction."),
    (1022, "Very Good", "A Nurse's Calling", "Nurse", "Information",
     "Reveals auras of survivors healing or being healed within 20-28 m; effectively neutralises healing-heavy teams and forces them to heal in unsafe spots."),
    (1023, "Very Good", "Sloppy Butcher", "General (all killers)", "Utility",
     "Basic attacks inflict Mangled and Hemorrhage, slowing healing speed and causing wounds to bleed more; strong on every killer with zero effort."),
    (1024, "Very Good", "Surge", "Demogorgon", "Gen Control",
     "Downing a survivor within 32 m of a generator causes it to explode and regress; completely free gen pressure on every down with no extra input."),
    (1025, "Very Good", "Hex: Pentimento", "Artist", "Hex",
     "Restoring a cleansed totem as a Pentimento totem applies stacking debuffs (slowdowns, aura blocks, speed boosts); brutally punishes totem-cleansing teams."),

    # ══ Decent (3★) ══════════════════════════════════════════════════════════

    (1026, "Decent", "Hex: Devour Hope", "Hag", "Hex",
     "Gain Exposed stacks after safe unhooks; at 5 tokens you can down survivors instantly and mori them; near-unbeatable when the totem survives."),
    (1027, "Decent", "Hex: Wretched Fate", "Dark Lord / Dracula", "Hex",
     "Survivors who touch a completed generator become Oblivious until another is completed; disrupts team coordination and information-sharing after gens pop."),
    (1028, "Decent", "Bamboozle", "Clown", "Chase",
     "Kicking a window blocks it for 20 seconds and increases your vault speed; dramatically reduces loop options in multi-window tiles."),
    (1029, "Decent", "Unforeseen", "Unknown", "Stealth",
     "After kicking a generator, gain Undetectable until it stops regressing; lets you silently reposition after a kick without alerting nearby survivors."),
    (1030, "Decent", "Friends 'til the End", "Good Guy / Chucky", "Information",
     "When your obsession is hooked, the new obsession's aura is revealed for 8 seconds; disrupts obsession builds and produces consistent free intel."),
    (1031, "Decent", "Furtive Chase", "Ghostface", "Stealth",
     "Hooking the obsession grants a token reducing your terror radius; stacks up to 4 times and can shrink your terror radius to near zero over the match."),
    (1032, "Decent", "Dissolution", "Dredge", "Chase",
     "A pallet that is fast-vaulted during a chase breaks 3 seconds later; progressively removes the safest pallets survivors rely on in key loops."),
    (1033, "Decent", "Call of Brine", "Onryo / Sadako", "Gen Control",
     "A kicked generator regresses faster for 60 seconds and sends a Loud Noise notification when touched; reliable intel on who is contesting your gens."),
    (1034, "Decent", "Scourge Hook: Floods of Rage", "Onryo / Sadako", "Information",
     "When a survivor is unhooked from a Scourge Hook, all other survivors' auras are revealed for 5 seconds; strong information after every Scourge unhook."),
    (1035, "Decent", "Discordance", "Legion", "Information",
     "Two or more survivors repairing the same generator triggers a Loud Noise notification and aura reveal; punishes grouping on generators mid-game."),
    (1036, "Decent", "Coup de Grâce", "Twins", "Chase",
     "Each completed generator grants a token enabling a much longer lunge; spending tokens provides a dramatic reach advantage in late-game chases."),
    (1037, "Decent", "Starstruck", "Trickster", "Utility",
     "While carrying a survivor, nearby healthy survivors become Exposed for 15 seconds; devastating when combined with Agitation to cover large areas."),
    (1038, "Decent", "Dragon's Grip", "Blight", "Gen Control",
     "After kicking a generator, the next survivor to touch it screams and briefly becomes Exposed; baits survivors off gens and punishes the first touch."),
    (1039, "Decent", "Enduring", "Hillbilly", "Chase",
     "Reduces pallet stun duration significantly; strong on any killer who gets stunned frequently and wants to maintain chase aggression at pallet-heavy tiles."),
    (1040, "Decent", "Fire Up", "Freddy / The Nightmare", "Utility",
     "Each completed generator gives a stacking speed bonus to many killer actions; scales into a powerful all-round buff when facing fast gen-rush teams."),
    (1041, "Decent", "Scourge Hook: Gift of Pain", "Cenobite / Pinhead", "Utility",
     "Survivors unhooked from a Scourge Hook suffer Hemorrhage and reduced healing speed for the rest of the match; cumulative punishment across multiple hooks."),
    (1042, "Decent", "Thrilling Tremors", "Ghostface", "Gen Control",
     "After picking up a survivor, all generators not being repaired are blocked for 16 seconds and their locations are revealed; passive gen-lock on carries."),
    (1043, "Decent", "Scourge Hook: Jagged Compass", "Houndmaster", "Gen Control",
     "Hooking on a Scourge Hook causes the nearest generator to regress for 30 seconds; completely passive gen regression requiring no additional input."),
    (1044, "Decent", "Hex: Crowd Control", "Trickster", "Hex",
     "Survivors who fast-vault a window in a chase trigger this hex, briefly blocking that window; discourages window-spamming at key loop tiles."),
    (1045, "Decent", "Predator", "Wraith", "Information",
     "Scratch marks appear slightly sooner and are brighter; minor but consistent tracking improvement for all basic-attack killers in close chases."),
    (1046, "Decent", "Rapid Brutality", "Xenomorph", "Chase",
     "After a basic attack, your movement speed no longer slows; lets you close the gap faster after landing a hit for immediate follow-up pressure."),
    (1047, "Decent", "Remember Me", "Freddy / The Nightmare", "End-Game",
     "Each hit on the obsession adds a token increasing exit gate opening time; builds to a massive 32-second gate delay that can close out close end-games."),
    (1048, "Decent", "Merciless Storm", "Onryo / Sadako", "Gen Control",
     "When a generator reaches 90% completion, trigger a demanding skill check; failure regresses the gen; creates clutch last-second intervention moments."),
    (1049, "Decent", "Terminus", "Mastermind / Wesker", "End-Game",
     "When end-game collapse begins, all uninjured survivors become Broken for 60 seconds; prevents last-second heals before escaping through exit gates."),
    (1050, "Decent", "Coulrophobia", "Clown", "Utility",
     "Survivors within your terror radius heal 50% slower; area-of-effect healing debuff that punishes grouped healing strategies when you patrol."),
    (1051, "Decent", "Phantom Fear", "Animatronic / Springtrap", "Information",
     "When a survivor exits the Oblivious status near you, they scream and their aura is revealed for a few seconds; reveals survivors escaping traps or Oblivious effects."),
    (1052, "Decent", "Hex: The Third Seal", "Hag", "Hex",
     "Survivors you damage with basic attacks become Blind; denies aura reading across the whole team and heavily hinders coordination."),
    (1053, "Decent", "Alien Instinct", "Xenomorph", "Information",
     "After hooking a survivor, the furthest survivor from the hook has their aura revealed for 6 seconds; passive information on the safest survivor after every hook."),
    (1054, "Decent", "Brutal Strength", "Trapper", "Utility",
     "Increases the speed at which you break generators, pallets and breakable walls by 20-30%; broadly useful quality-of-life for M1 killers who rely on pallet breaks."),
    (1055, "Decent", "Leverage", "Skull Merchant", "Utility",
     "Each injured or dead survivor reduces Scourge Hook sabotage repair speed; increasingly oppressive in 3-gen scenarios with multiple injured survivors."),
    (1056, "Decent", "Rancor", "Spirit", "End-Game",
     "After all generators are complete, reveal your obsession's aura periodically and gain the ability to mori them; strong finishing tool in the end-game."),
    (1057, "Decent", "Mindbreaker", "Demogorgon", "Gen Control",
     "Survivors repairing generators suffer Exhaustion while the gen is not at maximum regression rate; directly counters exhaustion-perk looping strategies."),
    (1058, "Decent", "Genetic Limits", "Singularity", "Chase",
     "After a Hindered survivor is no longer slowed, inflict Exhaustion on them; excellent on killers whose powers can apply the Hindered status effect."),
    (1059, "Decent", "Overwhelming Presence", "Doctor", "Utility",
     "Survivors within your terror radius deplete item charges much faster; punishes toolbox, flashlight and medkit-heavy teams with zone pressure."),
    (1060, "Decent", "Scourge Hook: Hangman's Trick", "Pig / Amanda Young", "Information",
     "Survivors who sabotage a Scourge Hook scream and reveal their aura for 8 seconds; deters and immediately exposes hook saboteurs near you."),
    (1061, "Decent", "Hex: Retribution", "Deathslinger", "Hex",
     "When a survivor cleanses any dull totem, all survivors become Oblivious for 30 seconds and the cleanser's aura is revealed; punishes dull totem cleanup."),
    (1062, "Decent", "Hex: Haunted Ground", "Spirit", "Hex",
     "Two hex totems spawn; when either is cleansed, all survivors become Exposed for 60 seconds and the cleansed totem is revealed; high-risk high-reward burst exposure."),
    (1063, "Decent", "Forever Entwined", "Ghoul / Kaneki", "Gen Control",
     "Power hits generate tokens; spend tokens to block generators near a hooked survivor briefly; a zoning tool tied to Ghoul's offensive power."),
    (1064, "Decent", "Zanshin Tactics", "Oni", "Information",
     "Reveals the auras of breakable pallets, vaultable windows and dropped pallets near you; valuable map-awareness tool for learning loop geometry."),
    (1065, "Decent", "Infectious Fright", "Plague", "Information",
     "Putting a survivor in the dying state causes all survivors within 24 m to scream and reveal their auras; excellent chain-down information on every down."),
    (1066, "Decent", "Ultimate Weapon", "Xenomorph", "Information",
     "After opening a locker, all survivors within 32 m scream and reveal their auras; one of the best freely-activated information perks available to all killers."),
    (1067, "Decent", "Languid Touch", "Lich / Vecna", "Chase",
     "Survivors affected by your power suffer Exhaustion for a period; excellent on Vecna whose varied spells can trigger this frequently and reliably."),
    (1068, "Decent", "Save the Best for Last", "The Shape / Myers", "Chase",
     "Attacking non-obsession survivors gains tokens that reduce hit-recovery time; spending tokens rewards efficient obsession tracking with faster follow-up attacks."),
    (1069, "Decent", "Hex: Plaything", "Cenobite / Pinhead", "Hex",
     "Each first-time hook activates a hex totem inflicting Oblivious on the hooked survivor; denies aura-reading to multiple survivors simultaneously."),
    (1070, "Decent", "Oppression", "Twins", "Gen Control",
     "Kicking a generator causes three other random generators to regress simultaneously; massive area-wide gen regression with one input."),
    (1071, "Decent", "Franklin's Demise", "Cannibal / Bubba", "Utility",
     "Survivors you hit lose their held item which depletes on the ground; destroys flashlights, medkits and toolboxes over time with no special play required."),

    # ══ Weak/Niche (2★) ══════════════════════════════════════════════════════

    (1072, "Weak/Niche", "Gearhead", "Deathslinger", "Information",
     "After downing a survivor, great skill checks on generators reveal the repairer's aura briefly; inconsistent information that requires survivor mistakes."),
    (1073, "Weak/Niche", "Spies from the Shadows", "General (all killers)", "Information",
     "Crows disturbed by survivors within 36 m send a notification; very minor tracking benefit with limited range and slow notification speed."),
    (1074, "Weak/Niche", "Human Greed", "Dark Lord / Dracula", "Stealth",
     "Opening a chest grants Undetectable for 30 seconds; extremely situational and only worthwhile in very specific locker or ambush builds."),
    (1075, "Weak/Niche", "Trail of Torment", "Executioner / Pyramid Head", "Stealth",
     "Kicking a generator grants Undetectable until it stops regressing; brief stealth window for repositioning after a kick."),
    (1076, "Weak/Niche", "Surveillance", "Pig / Amanda Young", "Information",
     "Regressing generators are highlighted in white; useful for tracking contested gens but provides no active benefit by itself."),
    (1077, "Weak/Niche", "Deerstalker", "General (all killers)", "Information",
     "Reveals the auras of dying survivors within 24 m; occasionally useful to confirm downed positions but rarely worth a full perk slot."),
    (1078, "Weak/Niche", "Deathbound", "Executioner / Pyramid Head", "Information",
     "When a survivor heals another far from you, the healer screams and their aura is briefly revealed; punishes long-distance healing with minor intel."),
    (1079, "Weak/Niche", "Hex: Huntress Lullaby", "Huntress", "Hex",
     "Hooks stack tokens progressively shrinking skill-check zones and eventually removing the warning sound; powerful if uncleansed but vulnerable early."),
    (1080, "Weak/Niche", "Hex: Face the Darkness", "Knight", "Hex",
     "Hooking a non-obsession survivor activates a hex; the furthest survivor screams periodically; steady information stream if the totem survives."),
    (1081, "Weak/Niche", "Nemesis", "Oni", "Utility",
     "Being blinded or pallet-stunned makes the responsible survivor your new obsession; disrupts obsession builds but has limited standalone value."),
    (1082, "Weak/Niche", "Machine Learning", "Singularity", "Gen Control",
     "Kicking a generator grants Undetectable; when that gen is repaired, instantly gain Bloodlust; fun snowball potential but very situational."),
    (1083, "Weak/Niche", "Weave Attunement", "Lich / Vecna", "Information",
     "When a survivor depletes an item, reveal all survivor auras for 30 seconds; incredibly powerful against item-heavy teams, near-useless otherwise."),
    (1084, "Weak/Niche", "Game Afoot", "Skull Merchant", "Chase",
     "Hitting the obsession grants a brief movement speed bonus; minor chase benefit that rarely changes game outcomes."),
    (1085, "Weak/Niche", "Dominance", "Dark Lord / Dracula", "Information",
     "After your power hits a survivor, nearby generators are highlighted briefly; minor gen-location intel that is too short-lived to be reliable."),
    (1086, "Weak/Niche", "Spirit Fury", "Spirit", "Chase",
     "The second pallet stun in a chase breaks the pallet automatically; best combined with Enduring to negate pallet cost entirely in looping chases."),
    (1087, "Weak/Niche", "Make Your Choice", "Pig / Amanda Young", "Chase",
     "An unhooked survivor far from you becomes Exposed for 60 seconds; powerful on killers who can quickly reach distant hooks, weak on slow killers."),
    (1088, "Weak/Niche", "Hubris", "Knight", "Chase",
     "Being stunned by a pallet makes the responsible survivor Exposed for 15 seconds; punishes stun play but requires eating a pallet stun first."),
    (1089, "Weak/Niche", "Play with Your Food", "The Shape / Myers", "Chase",
     "Each chase left without a hit grants tokens of movement speed; counter-intuitively rewards letting survivors go rather than finishing chases."),
    (1090, "Weak/Niche", "I'm All Ears", "Ghostface", "Information",
     "After a survivor performs a rushed vault during a chase, reveal their aura for 6 seconds; punishes panic-vaulting but requires an active chase."),
    (1091, "Weak/Niche", "Monitor & Abuse", "Doctor", "Stealth",
     "Outside chases your terror radius shrinks; in chases your field of view expands; decent stealth approach tool outclassed by most dedicated alternatives."),
    (1092, "Weak/Niche", "Forced Hesitation", "Singularity", "Chase",
     "Downing a survivor Hinders all nearby standing survivors for 5 seconds; minor area slow on grouped survivors close to the downed target."),
    (1093, "Weak/Niche", "Forced Penance", "Executioner / Pyramid Head", "Utility",
     "Survivors who take a protection hit become Broken for 80 seconds; counters protection-hit farming but has no value against survivors playing solo."),
    (1094, "Weak/Niche", "Superior Anatomy", "Mastermind / Wesker", "Chase",
     "After a survivor vaults, you can vault the same spot faster for a few seconds; minor chase utility that rarely wins tiles on its own."),
    (1095, "Weak/Niche", "Batteries Included", "Good Guy / Chucky", "Utility",
     "Gain Haste when a survivor touches a generator near you; very minor speed boost with inconsistent activation conditions."),
    (1096, "Weak/Niche", "Darkness Revealed", "Dredge", "Information",
     "Opening a locker reveals survivor auras within 16 m for 3 seconds; useful in locker-centric builds but too situational for general use."),
    (1097, "Weak/Niche", "Whispers", "General (all killers)", "Information",
     "Every 30 seconds, a notification triggers if a survivor is within 32 m; slow and imprecise tracking with no directional information provided."),
    (1098, "Weak/Niche", "Awakened Awareness", "Mastermind / Wesker", "Information",
     "While carrying a survivor, reveal all survivor auras within 32 m; great for intercepting rescuers but only active during the carry."),
    (1099, "Weak/Niche", "Dark Devotion", "Plague", "Stealth",
     "Hitting the obsession transfers your terror radius to them for 30 seconds; complex stealth mechanic requiring specific setups to use effectively."),
    (1100, "Weak/Niche", "THWACK!", "Skull Merchant", "Utility",
     "After picking up a survivor near a Scourge Hook, gain brief Haste; minor mobility perk with very limited activation conditions."),
    (1101, "Weak/Niche", "Dark Arrogance", "Lich / Vecna", "Stealth",
     "Vaulting a window grants brief Undetectable; very situational stealth window requiring a chase that goes through vaultable windows."),
    (1102, "Weak/Niche", "Blood Warden", "Freddy / The Nightmare", "End-Game",
     "Hooking a survivor during end-game collapse blocks both exit gates for 30 seconds; high-risk end-game perk requiring a hook during the collapse itself."),
    (1103, "Weak/Niche", "Scourge Hook: Monstrous Shrine", "General (all killers)", "Utility",
     "Hooks near Scourge Hooks grant bonus Bloodpoints and slightly accelerate hook stages; passive minor bonus with limited active impact on survivor behaviour."),
    (1104, "Weak/Niche", "Overcharge", "Doctor", "Gen Control",
     "Kicking a generator causes a very difficult skill check; failure results in extra regression; countered entirely by experienced survivors."),
    (1105, "Weak/Niche", "Ravenous", "Krasue", "Chase",
     "After hooking a survivor, gain a brief burst of Haste; minor post-hook mobility boost that barely changes chase or patrol outcomes."),
    (1106, "Weak/Niche", "Bitter Murmur", "General (all killers)", "Information",
     "Completed generators reveal the auras of nearby survivors for 5 seconds; reactive information that arrives after the fact and is rarely actionable."),
    (1107, "Weak/Niche", "Thanatophobia", "Nurse", "Utility",
     "Each injured, dying or hooked survivor applies a small action-speed penalty; requires a large number of injured survivors to reach meaningful slow values."),
    (1108, "Weak/Niche", "Dying Light", "The Shape / Myers", "Utility",
     "Hooking the obsession gives all other survivors a stacking action penalty; complex to trigger and the obsession itself gains a counter-bonus."),
    (1109, "Weak/Niche", "Blood Echo", "Oni", "Chase",
     "Putting a survivor in the dying state removes all Exhaustion tokens from Exhausted survivors; specifically counters exhaustion-perk heavy teams."),
    (1110, "Weak/Niche", "Lightborn", "Hillbilly", "Utility",
     "Greatly reduces blindness duration from flashlights; absolute hard counter to flashlight-user teams, otherwise dead weight in every other match."),
    (1111, "Weak/Niche", "Cruel Limits", "Demogorgon", "Chase",
     "Completed generators block all windows and vaults in their area for 30 seconds; zone control that only activates after generators are already finished."),
    (1112, "Weak/Niche", "Mad Grit", "Legion", "Chase",
     "Removes attack cooldown on a missed basic attack while carrying a survivor; counters bodyblock rescues but rarely activates in normal gameplay."),
    (1113, "Weak/Niche", "Hysteria", "Nemesis", "Information",
     "When a healthy survivor is injured, all already-injured survivors become Oblivious for 30 seconds; information denial that requires a grouped team."),
    (1114, "Weak/Niche", "Beast of Prey", "Huntress", "Stealth",
     "Reaching maximum Bloodlust grants Undetectable and a Bloodpoint bonus; difficult to consistently activate since Bloodlust is rare at high MMR."),
    (1115, "Weak/Niche", "Unbound", "Unknown", "Information",
     "While using your power, reveal auras of survivors further than 12 m; informational perk tied entirely to Unknown's specific power mechanic."),
    (1116, "Weak/Niche", "All-Shaking Thunder", "Houndmaster", "Gen Control",
     "After hooking a survivor, the next generator you kick receives extra regression; a one-time bonus per hook that provides minor additional regression."),
    (1117, "Weak/Niche", "Hoarder", "Twins", "Information",
     "When a survivor picks up an item from a chest or the ground, receive a noise notification and aura reveal; punishes item collection in a limited radius."),
    (1118, "Weak/Niche", "Septic Touch", "Dredge", "Utility",
     "Survivors performing healing actions within your terror radius gain Mangled and Hemorrhage; area-based healing denial that requires proximity."),
    (1119, "Weak/Niche", "Knock Out", "Cannibal / Bubba", "Utility",
     "Non-obsession survivors you down cannot be found by other survivors' auras within 24 m; makes solo-rescue attempts harder and pairs well with Agitation."),
    (1120, "Weak/Niche", "Wandering Eye", "Krasue", "Information",
     "After kicking a generator, all survivor auras are briefly revealed for 2 seconds; extremely short reveal window that is hard to act on."),
    (1121, "Weak/Niche", "Iron Maiden", "Legion", "Information",
     "You open lockers faster; survivors found inside become Exposed and their aura is revealed for 30 seconds; enables locker-patrol builds."),
    (1122, "Weak/Niche", "Hex: Nothing But Misery", "Ghoul / Kaneki", "Hex",
     "Power hits stack Broken on survivors; potent on Ghoul whose Kagune can hit multiple survivors rapidly, near-useless on killers without a power hit."),
    (1123, "Weak/Niche", "Help Wanted", "Animatronic / Springtrap", "Information",
     "After kicking a generator, reveal survivor auras within 24 m briefly; minor aura information tied to gen kicks."),
    (1124, "Weak/Niche", "None Are Free", "Ghoul / Kaneki", "Utility",
     "After hitting survivors multiple times with your power, apply additional effects; power-specific perk best suited to Ghoul's multi-hit playstyle."),
    (1125, "Weak/Niche", "Hex: Overture of Doom", "Krasue", "Hex",
     "Breaking a pallet converts the nearest dull totem into a Hex: Overture of Doom totem; activates a chain effect but requires totem survival."),
    (1126, "Weak/Niche", "Hex: Two Can Play", "Good Guy / Chucky", "Hex",
     "When a survivor blinds you, inflict Blind on that survivor for the same duration; hard counter to dedicated flashlight users, niche otherwise."),
    (1127, "Weak/Niche", "Unrelenting", "General (all killers)", "Chase",
     "Reduces missed basic attack cooldown; marginal benefit and generally outclassed by other chase perks."),
    (1128, "Weak/Niche", "Territorial Imperative", "Huntress", "Information",
     "While in the basement, receive notifications when survivors enter the killer shack or main building; very limited detection area."),
    (1129, "Weak/Niche", "Iron Grasp", "General (all killers)", "Utility",
     "Reduces survivor struggling and Boil Over resistance while carrying; minor counter to struggling survivors, rarely a priority pick."),
    (1130, "Weak/Niche", "Shadowborn", "Wraith", "Utility",
     "Increases field of view permanently; passive quality-of-life perk outclassed by perks with active information or chase benefits."),
    (1131, "Weak/Niche", "Bloodhound", "Wraith", "Information",
     "Blood pools are more visible and scratch marks are slightly brighter; very minor tracking improvement barely noticeable at high level."),
    (1132, "Weak/Niche", "Unnerving Presence", "Trapper", "Utility",
     "Survivors performing actions within your terror radius face reduced skill-check zones; mild penalty that skilled survivors learn to play around quickly."),
    (1133, "Weak/Niche", "Stridor", "Nurse", "Information",
     "Increases the volume of survivor breathing and grunts of pain; useful for tracking injured survivors by sound but outclassed by aura perks."),

    # ══ Terrible (1★) ════════════════════════════════════════════════════════

    (1134, "Terrible", "Insidious", "General (all killers)", "Stealth",
     "Standing still makes you Undetectable; only viable as a rare basement ambush gimmick and never a reliable competitive pick."),
    (1135, "Terrible", "No Quarter", "Houndmaster", "Utility",
     "After hooking a survivor, gain brief Haste; negligible mobility bonus that almost never changes game outcomes."),
    (1136, "Terrible", "Distressing", "General (all killers)", "Utility",
     "Massively increases your terror radius and grants bonus Bloodpoints; larger terror radius alerts survivors much earlier, actively hurting your game."),
    (1137, "Terrible", "Undone", "Unknown", "Gen Control",
     "After your power affects a survivor, generators regress slightly; power-specific minor regression that barely registers against competent teams."),
    (1138, "Terrible", "Haywire", "Animatronic / Springtrap", "Gen Control",
     "Your power charge near a generator causes brief regression when reaching a threshold; extremely situational, inconsistent and minor in effect."),
    (1139, "Terrible", "Shattered Hope", "General (all killers)", "Utility",
     "Instantly destroys a Boon totem within your terror radius; only valuable against Boon-heavy teams and otherwise a complete waste of a perk slot."),
]


def get_killer_perks():
    """Return KILLER_PERKS as a list of dicts matching the PERKS format."""
    return [
        {
            "id":          row[0],
            "tier":        row[1],
            "name":        row[2],
            "character":   row[3],
            "category":    row[4],
            "description": row[5],
        }
        for row in KILLER_PERKS_RAW
    ]
